```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r}
library(harmony)
library(DropletUtils)
library(Seurat)
library(tidyverse)
library(dplyr)
library(stringr)
library(knitr)
library(DoubletFinder)
library(SoupX)
library(scCustomize)
library(DESeq2)
# library(devtools)
# install_github("immunogenomics/harmony")
```

## Second draft of integration script (first in log33)

```{r}
#Load all of the relevant data. This will be soup-less, doublet-filtered Seruat objects from each paper

load("Rdata/Ver_singlets_merged.RData")
load("Rdata/Xim_singlets_mergedRedux.Rdata") #Using Redux info (from new reference)
load("Rdata/Slo_singlets_merged.RData")
Slo_singlets_merged<-Slota_singlets_merged
rm(Slota_singlets_merged)
gc()
#What would the size of this be in memory?
  #33.75 GB

#Set active assays to RNA
DefaultAssay(Slo_singlets_merged) <- "RNA"
DefaultAssay(Xim_singlets_merged) <- "RNA"
DefaultAssay(Ver_singlets_merged) <- "RNA"
```

## Need ot subset the astrocytes from each dataset first....?






## Add metadata about treatment

```{r}
#Add metadata on treatment, adapted from Chat GPT
#Slota
sampleLabs_Slota<- names(Slo_singlets_merged@active.ident)

treat_detect_Slota <- case_when(
  str_detect(sampleLabs_Slota, "RML.*HP*") ~ "PRION_HP",
  str_detect(sampleLabs_Slota, "PBS.*HP*") ~ "CTRL_HP",
  str_detect(sampleLabs_Slota, "RML.*CX*") ~ "PRION_CX",
  str_detect(sampleLabs_Slota, "PBS.*CX*") ~ "CTRL_CX",
  TRUE ~ NA_character_
)

Slo_singlets_merged@meta.data$treatment<-treat_detect_Slota
Idents(object=Slo_singlets_merged)<-"treatment"
rm(treat_detect_Slota, sampleLabs_Slota)
table(Slo_singlets_merged$treatment)
Slo_singlets_merged@meta.data$source<-"Slota"

#Ximerakis
sampleLabs_Xim<- names(Xim_singlets_merged@active.ident)

treat_detect_Xim <- case_when(
  str_detect(sampleLabs_Xim, "OX*") ~ "AGED",
  str_detect(sampleLabs_Xim, "YX*") ~ "YOUNG",
  TRUE ~ NA_character_
)

Xim_singlets_merged@meta.data$treatment<-treat_detect_Xim
Idents(object=Xim_singlets_merged)<-"treatment"
rm(treat_detect_Xim, sampleLabs_Xim)
Xim_singlets_merged@meta.data$source<-"Ximerakis"

#Verity
sampleLabs_Verity<-names(Ver_singlets_merged@active.ident)

#From Chat GPT
treat_detect_Verity <- case_when(
  str_detect(sampleLabs_Verity, "sample11") ~ "AGEING",
  str_detect(sampleLabs_Verity, "sample1") ~ "CTRL_HP",
  str_detect(sampleLabs_Verity, "sample2") ~ "CTRL_HP",
  str_detect(sampleLabs_Verity, "sample5") ~ "PRION_HP",
  str_detect(sampleLabs_Verity, "sample6") ~ "PRION_HP",
  str_detect(sampleLabs_Verity, "sample9") ~ "AGEING",
  TRUE ~ NA_character_
)
#
Ver_singlets_merged@meta.data$treatment<-treat_detect_Verity

#FIXME may not be needed if the integration workflow specifies what to consider anyway
Idents(object=Ver_singlets_merged)<-"treatment"
rm(sampleLabs_Verity, treat_detect_Verity)
Ver_singlets_merged@meta.data$source<-"Verity"

gc()
```


```{r}
#split, then subset and merge the relevant data into the comparison datasets as detailed in the comparison table above
Xim_list<-SplitObject(Xim_singlets_merged, split.by = "treatment")
Slo_list<-SplitObject(Slo_singlets_merged, split.by = "treatment")
Ver_list<-SplitObject(Ver_singlets_merged, split.by = "treatment")
rm(Xim_singlets_merged, Slo_singlets_merged, Ver_singlets_merged)
gc()
```

```{r}
#COMPARISON 1 Hippocampus DEG between datasets (Verity and terminal)
#list of samples to merge
comp1<-c(Slo_list$CTRL_HP,Slo_list$PRION_HP,Ver_list$CTRL_HP, Ver_list$PRION_HP)

# Merge raw samples, adapted from here https://hbctraining.github.io/scRNA-seq_online/lessons/06a_integration_harmony.html
comp1_merged <-Merge_Seurat_List(list_seurat=comp1)

rm(comp1)
gc()

# Perform log-normalization and feature selection, as well as SCT normalization on global object
comp1_merged <- comp1_merged %>%
    NormalizeData() %>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
    ScaleData() #%>%
    #SCTransform(vars.to.regress = c("mitoRatio")) #FIXME do we need this?

# Calculate PCs using variable features determined by SCTransform (3000 by default) ##I have changed the assay to RNA and reduced pcs to 30 from 50
#Visualise the data
comp1_merged <- RunPCA(comp1_merged, assay = "RNA", npcs = 30)
#Elbowplot shows around 20 PCs are enough

comp1_merged<- RunUMAP(comp1_merged, reduction = "pca", dims = 1:20)
DimPlot(comp1_merged, reduction='umap', group.by = 'treatment', raster=F)+ggtitle("Verity and Slota Hippocampal data", subtitle = "Before harmony integration")

#Add proper sample labels




comp1_harmonized <- RunHarmony(comp1_merged, group.by.vars = c("treatment"), #FIXME variable names to integrate on
				reduction = "pca", assay.use = "RNA", reduction.save = "harmony", verbose=T)

comp1_harmonized <- 
  RunUMAP(comp1_harmonized, reduction = "harmony", dims = 1:20) %>%
  FindNeighbors(reduction='harmony', dims=1:20) %>%
  FindClusters(resolution=c(0.2,0.3,0.5,0.7,1))

#This gives a good level of clustering 
comp1_harmonized@active.ident<-comp1_harmonized@meta.data$RNA_snn_res.0.2

#Visualisation
dimplotcolours=c(
  'NA',
  rgb(0.53, 0.81, 0.95, 0.5),
  rgb(0.23, 0.51, 0.75, 0.5), #uncomment to give sample 11 colour, but this covers most of the data
  rgb(0.95, 0.27, 0.14, 0.5)
  
)


DimPlot(comp1_harmonized, label = TRUE, repel = TRUE, raster=F, split.by = 'treatment')+ggtitle("Verity and Slota Hippocampal data", subtitle = "After harmony integration")#+scale_color_manual(values = dimplotcolours)

```


## Untested



```{r}
#COMPARISON 2
#list of samples to merge
comp2a<-list(subset(Slo_singlets_merged,subset=sample==c("RML122HP","RML142HP","RML133HP","RML132HP","RML138HP","RML145HP","RML140HP"))) #FIXME check sample names
comp2b<-list(subset(Ver_singlets_merged,subset=sample==c("sample5", "sample6")))
comp2c<-list(subset(Ver_singlets_merged,subset=sample==c("OX1X","OX2X","OX3X", "OX4X","OX5X","OX6X","OX7X","OX8X")))

comp2<-list(comp2a,comp2b, comp2c)
# Merge raw samples, adapted from here https://hbctraining.github.io/scRNA-seq_online/lessons/06a_integration_harmony.html
comp2_merged <-Merge_Seurat_List(list_seurat=comp1) 

rm(list(comp2))
gc()

# Perform log-normalization and feature selection, as well as SCT normalization on global object
comp2_merged <- comp2_merged %>%
    NormalizeData() %>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
    ScaleData() %>%
    SCTransform(vars.to.regress = c("mitoRatio")) #FIXME do we need this?

# Calculate PCs using variable features determined by SCTransform (3000 by default)
comp2_merged <- RunPCA(comp2_merged, assay = "SCT", npcs = 50)

comp2_merged_harmonized <- RunHarmony(comp2_merged, 
				group.by.vars = c("sample_id", "experiment_date"), #FIXME variable names to integrate on
				reduction = "pca", assay.use = "SCT", reduction.save = "harmony")

comp2_merged_harmonized <- RunUMAP(comp2_merged_harmonized, reduction = "harmony", assay = "SCT", dims = 1:40)

```
