---
title: "Slota emptydrops attempt workflow"
output: html_document
date: "2023-06-01"
---

## Slota loading for emptydrop calc


```{r include=FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DropletUtils")
library(DropletUtils)

BiocManager::install("Seurat")
library(Seurat)
library(tidyverse)

#library(ggplot2)

library(dplyr)
library(stringr)
library(knitr)

remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
library(DoubletFinder)

if (!require("SoupX", quietly = TRUE))
    install.packages("SoupX")
library(SoupX)

if (!require("scCustomize", quietly = TRUE))
    install.packages("scCustomize")
library(scCustomize)
```



```{r}
# Create list of folder names
sample_names<- readLines("/home/s2268606/University_Directories/Project_23/External_datasets/Slota_paper/Slota_samples.txt")
#rename them for Slota folders
folder_names <- paste0(sample_names,"dir")

# Loop through each folder to process it
for (folder_name in folder_names) {
  folder_path=paste0("/home/s2268606/University_Directories/Project_23/External_datasets/Slota_paper/SCP1962/other/raw_stuff/",folder_name)
  
  
  current_data<-Read10X(data.dir =folder_path)
  current_obj<-CreateSeuratObject(counts=current_data, project="Slota")
  
  out<-emptyDrops(current_obj@assays$RNA@counts,niters= 10000)
  is.cell <- out$FDR <= 0.001
  sum(is.cell, na.rm=TRUE)
  table(Sig=is.cell, Limited=out$Limited)
  
  current_cells <- current_obj@assays$RNA@counts[,which(is.cell),drop=FALSE]
  current_drops<- current_obj@assays$RNA@counts[,which(is.cell),drop=TRUE]
  
  
  assign(paste0(folder_name,"_cells"), current_cells)
  assign(paste0(folder_name,"_object"), current_obj)
  assign(paste0(folder_name,"_drops"), current_drops)
  
}
```

```{r}
metadata_test<-current_obj@meta.data
#Saving cell barcodes as metainfo
metadata_test$cells<-rownames(metadata_test)
metadata_test <- metadata_test %>%
dplyr::rename(nUMI = nCount_RNA,
nGene = nFeature_RNA)
metadata_test %>%
ggplot(aes( x=nGene, fill= nGene)) +
geom_density(alpha = 0.2) +
theme_classic() +
scale_x_log10() +
geom_vline(xintercept = 300)+
ggplot2::ggtitle("Distribution of genes per cell", subtitle="Ximerakis, filtered to minimum 20 genes")
```

