## 1 Load the packages

```{r}
library(DropletUtils)
library(Seurat)
library(tidyverse)
library(dplyr)
library(stringr)
library(knitr)
library(DoubletFinder)
library(SoupX)
library(scCustomize)
install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('metap')
library(metap)
```

```{r}
load("Rdata/Ver_singlets_merged.RData")
```

### 2 Make metadata for treatment

```{r}
sampleLabs<-names(Ver_singlets_merged@active.ident)

#FIXME change these to be treatment levels of experimental setup

#Assigning names to the samples to keep identity
#From Chat GPT
treat_detect <- case_when(
  str_detect(sampleLabs, "sample11") ~ "AGEING",
  str_detect(sampleLabs, "sample1") ~ "NBH",
  str_detect(sampleLabs, "sample2") ~ "NBH",
  str_detect(sampleLabs, "sample5") ~ "ME7",
  str_detect(sampleLabs, "sample6") ~ "ME7",
  str_detect(sampleLabs, "sample9") ~ "AGEING",
  TRUE ~ NA_character_
)
#
Ver_singlets_merged@meta.data$treatment<-treat_detect

#FIXME may not be needed if the integration workflow specifies what to consider anyway
Idents(object=Ver_singlets_merged)<-"treatment"
rm(sampleLabs, treat_detect)
```

## 3 Setup

```{r}
# adapted from https://satijalab.org/seurat/articles/integration_introduction.html

#FIXME set the RNA assay as active
DefaultAssay(Ver_singlets_merged) <- "RNA"

# split the dataset into a list of three seurat objects (ME7, NBH, AGEING)
Ver_list<-SplitObject(Ver_singlets_merged, split.by = "treatment")
rm(Ver_singlets_merged)
gc()

Ver_list_backup<-Ver_list

# normalize and identify variable features for each dataset independently
Ver_list <- lapply(X = Ver_list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = Ver_list,verbose = TRUE)
```

### 3.a RPCA options

from [<https://satijalab.org/seurat/articles/integration_rpca.html>]

```{r}

#Perform PCA on the data individually before integration
Ver_list <- lapply(X = Ver_list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = TRUE)
    x <- RunPCA(x, features = features, verbose = TRUE)
})


#Use RPCA
Verity.anchors <- FindIntegrationAnchors(object.list = Ver_list, anchor.features = features, verbose=TRUE, reduction='rpca')

# this command creates an 'integrated' data assay
Verity.combined <- IntegrateData(anchorset = Verity.anchors, verbose=TRUE)
```

```{r}
# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(Verity.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
Verity.combined <- ScaleData(Verity.combined, verbose = FALSE)
Verity.combined <- RunPCA(Verity.combined, npcs = 30, verbose = FALSE)
ElbowPlot(Verity.combined, ndims=30)+ggtitle("Elbowplot of Integrated Verity data", subtitle = "RunPCA npcs=30, RPCA workflow")

Verity.combined <- RunUMAP(Verity.combined, reduction = "pca", dims = 1:20)
Verity.combined <- FindNeighbors(Verity.combined, reduction = "pca", dims = 1:20)
Verity.combined <- FindClusters(Verity.combined, resolution = 1)

save(Verity.combined,file="Rdata/Verity.self_integrated_RPCA.Rdata")
```

```{r}
# Visualization
p1 <- DimPlot(Verity.combined, reduction = "umap", split.by = "treatment", raster=FALSE)+ ggtitle("Integrated Verity data, split by treatement", subtitle="RPCA,Clustering resolution 1, 30 PCs used")

#Check for sample batch effects (shouldn't see this in an integrated dataset). The colou pallete hides sample11 because it covers everything

# dimplotcolours=c(
#   rgb(0.53, 0.81, 0.95, 0.5),
#   'NA',
#   #rgb(0.23, 0.51, 0.75, 0.5), #uncomment to give sample 11 colour, but this covers most of the data
#   rgb(0.95, 0.27, 0.14, 0.5),
#   rgb(0.61, 0.09, 0.78, 0.5),
#   rgb(0.44, 0.83, 0.15, 0.5),
#   rgb(0.92, 0.67, 0.12, 0.5),
#   rgb(0.03, 0.65, 0.40, 0.5)
# )
# p2 <- DimPlot(Verity.combined, reduction = "umap", group.by = "sample", raster=FALSE +scale_color_manual(values = dimplotcolours))

#This plot would be to label by cell type, not useable as I haven't used singleR yet
# p3 <- DimPlot(Verity.combined, reduction = "umap", group.by = "seurat_annotations", label = TRUE,repel = TRUE, raster=FALSE)


#show the plots
p1 #+ p2 +p3
```

```{r}
DefaultAssay(Verity.combined)<-"RNA"

#Check for a gene of interest in the data's geneset
filtered_gene_names[grep("^Slc1a2", filtered_gene_names)]

#try to identify astrocytes  with genes (Aldh1l1, Syp, Csf1r,Tmem119, Map2, Gfap)
FeaturePlot(Verity.combined,features=c("Aldh1l1","Gfap","Slc1a2"), raster=F)+ggtitle("Integrated Verity data, labelled with astrocyte gene markers", subtitle="RPCA,Clustering resolution 1, 20 PCs used")
#+scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral"))) + ggtitle("ALDH1 for astrocytes")
```

### 3. b Default workflow with CCA

```{r}

#identify anchors
Verity.anchors_CCA <- FindIntegrationAnchors(object.list = Ver_list, anchor.features = features, verbose=TRUE)

# this command creates an 'integrated' data assay using the anchors
Verity.combined_CCA <- IntegrateData(anchorset = Verity.anchors_CCA)

#save the object
#save(Verity.combined_CCA,file="Rdata/Verity.self_integrated.Rdata")

#Perform integrated analysis
# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(Verity.combined_CCA) <- "integrated"

# Run the standard workflow for visualization and clustering
Verity.combined_CCA <- ScaleData(Verity.combined_CCA, verbose = FALSE)
Verity.combined_CCA <- RunPCA(Verity.combined_CCA, npcs = 30, verbose = FALSE)
ElbowPlot(Verity.combined_CCA)
Verity.combined_CCA <- RunUMAP(Verity.combined_CCA, reduction = "pca", dims = 1:20)
Verity.combined_CCA <- FindNeighbors(Verity.combined_CCA, reduction = "pca", dims = 1:20)
Verity.combined_CCA <- FindClusters(Verity.combined_CCA, resolution = 0.5)

# Visualization
p1CCA <- DimPlot(Verity.combined_CCA, reduction = "umap", group.by = "treatment", raster=F)
p2CCA <- DimPlot(Verity.combined_CCA, reduction = "umap", label = TRUE, repel = TRUE, raster=F)
p1CCA + p2CCA

#Visualise treatments side by side
DimPlot(Verity.combined_CCA, reduction = "umap", split.by = "treatment", raster=F)
```

## 4. Verity DE

relies on good clustering, needs to be cdone after the splitting has been done properly and clusters are idenitfied.

```{r}
srat <- NormalizeData(srat)
srat <- FindVariableFeatures(srat, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(srat)
srat <- ScaleData(srat, features = all.genes)
```
